In [162]:
import pandas as pd

# Combine 397 pages of scanlator groups

In [84]:
df_scanlator = pd.DataFrame()
for i in range(1,397):
    df_new = pd.read_csv('scanlator_group_new_{}.csv'.format(i))
    df_scanlator = df_scanlator.append(df_new, sort=False)
df_scanlator

,Unnamed: 0,Name,Active or not,Release Frequency,Number of Release,Total Series,First Update,Lastest Update,Action,Adult,...,Shoujo Ai,Shounen,Shounen Ai,Slice of Life,Smut,Sports,Supernatural,Tragedy,Yaoi,Yuri
0,0,#1onlii,No,Inactive Group,9,9,01/03/15,03/22/15,2,1,...,0,4,0,2,0,0,3,1,0,0
1,0,#dropout,Yes,Often. About every 3.2 day(s),1033,26,08/02/16,08/03/20,3,0,...,0,13,0,10,0,0,8,0,0,0
2,0,#EverydayHeroes Scans,Yes,Often. About every 5.2 day(s),392,12,08/29/15,08/01/20,3,0,...,0,0,0,2,0,1,3,0,0,0
3,0,#got-nyu?,No,Inactive Group,0,0,no date,no date,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,#Hassasin,No,Inactive Group,4,2,05/23/19,12/30/19,1,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18,0,김지우JK,Yes,Often. About every 4 day(s),17,1,06/15/19,08/04/20,1,0,...,0,1,0,0,0,0,0,1,0,0
19,0,잠깐만,No,Inactive Group,1,1,02/03/20,02/03/20,1,0,...,0,1,0,0,0,0,0,0,0,0
20,0,情深緣淺 Tinh Tham Duyen Thien,Yes,Infrequently,4,3,03/15/20,06/23/20,0,1,...,0,0,1,2,0,0,3,1,3,0
21,0,灰猫,Yes,Often. About every 1 to 2 day(s),5,1,06/12/20,06/24/20,0,0,...,0,0,1,0,0,0,0,0,0,0
22,0,顔掌 Translations,No,Inactive Group,3,1,08/17/10,08/03/12,1,0,...,0,1,0,0,0,0,0,0,0,0

In [44]:
df_scanlator.to_csv('scanlator_all.csv')

In [42]:
pd.set_option('display.max_columns', None)

# Combine 400 pages of licensed series

In [94]:
#change the name of the first page csv file
df_start = pd.read_csv("title_license_1.csv")
df_start.to_csv('title_license_1')

In [154]:
df_title = pd.DataFrame()

In [155]:
for i in range(1,402):
    df_new = pd.read_csv("title_license_{}".format(i))
    df_title = df_title.append(df_new, sort = False)

In [156]:
df_title

,Unnamed: 0,Unnamed: 0.1,ID,Title,Type,Number of Scanlation group,Awarded,Japanese publihsers,Oneshot,Scan start day,...,Shoujo Ai,Shounen,Shounen Ai,Slice of Life,Smut,Sports,Supernatural,Tragedy,Yaoi,Yuri
0,0,0.0,165168,#Killstagram,Manhwa,1,False,Naver,False,04/04/20,...,0,0,0,0,0,0,0,0,0,0
1,1,0.0,159940,#Uraomote danshi to Hatsukoi no Hajimekata,Manga,0,False,Brite Shuppan,False,Pass,...,0,0,0,0,1,0,0,0,0,0
2,2,0.0,153558,"'Tis Time for ""Torture,"" Princess",Manga,3,False,Shueisha,False,05/24/19,...,0,1,0,1,0,0,0,0,0,0
3,3,0.0,34241,"""Bungaku Shoujo"" (Novel)",Novel,1,True,Enterbrain,False,12/11/08,...,0,1,0,0,0,0,0,0,0,0
4,4,0.0,131967,"""Do es""",Manga,0,False,futurecomics,True,Pass,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,0,NaN,110961,Sabaku ni Kieta Tsuma,Manga,0,False,Harlequin,False,Pass,...,0,0,0,0,0,0,0,0,0,0
8,0,NaN,49842,Shibito no Koiwazurai,Manga,1,False,Asahi Sonorama,False,08/21/15,...,0,0,0,0,0,0,1,1,0,0
9,0,NaN,99938,Suki darake,Manga,4,False,Wani Magazine,False,09/07/11,...,0,0,0,0,0,0,0,0,0,0
10,0,NaN,170300,Teach Me! (Newra),Manhwa,0,False,Lezhin,False,Pass,...,0,0,1,0,0,0,0,0,1,0
11,0,NaN,35759,Fairies,Manga,0,False,Kodansha,False,Pass,...,0,0,0,0,0,0,0,0,0,0

# There are dublicated rows in both scanlator and series dataframe

## Check how many rows were duplicated in title dataframe

In [157]:
list_id_title = [i for i in df_title['ID']]

In [158]:
len(set([x for x in list_id_title if list_id_title.count(x) > 1]))

331

## Drop the duplicated rows in title dataframe

In [130]:
df_title_test = df_title.copy()

In [159]:
df_title_test = df_title_test.drop_duplicates(subset="ID")
df_title_test

,Unnamed: 0,Unnamed: 0.1,ID,Title,Type,Number of Scanlation group,Awarded,Japanese publihsers,Oneshot,Scan start day,...,Shoujo Ai,Shounen,Shounen Ai,Slice of Life,Smut,Sports,Supernatural,Tragedy,Yaoi,Yuri
0,0,0.0,165168,#Killstagram,Manhwa,1,False,Naver,False,04/04/20,...,0,0,0,0,0,0,0,0,0,0
1,1,0.0,159940,#Uraomote danshi to Hatsukoi no Hajimekata,Manga,0,False,Brite Shuppan,False,Pass,...,0,0,0,0,1,0,0,0,0,0
2,2,0.0,153558,"'Tis Time for ""Torture,"" Princess",Manga,3,False,Shueisha,False,05/24/19,...,0,1,0,1,0,0,0,0,0,0
3,3,0.0,34241,"""Bungaku Shoujo"" (Novel)",Novel,1,True,Enterbrain,False,12/11/08,...,0,1,0,0,0,0,0,0,0,0
4,4,0.0,131967,"""Do es""",Manga,0,False,futurecomics,True,Pass,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,0,NaN,110961,Sabaku ni Kieta Tsuma,Manga,0,False,Harlequin,False,Pass,...,0,0,0,0,0,0,0,0,0,0
8,0,NaN,49842,Shibito no Koiwazurai,Manga,1,False,Asahi Sonorama,False,08/21/15,...,0,0,0,0,0,0,1,1,0,0
9,0,NaN,99938,Suki darake,Manga,4,False,Wani Magazine,False,09/07/11,...,0,0,0,0,0,0,0,0,0,0
10,0,NaN,170300,Teach Me! (Newra),Manhwa,0,False,Lezhin,False,Pass,...,0,0,1,0,0,0,0,0,1,0
11,0,NaN,35759,Fairies,Manga,0,False,Kodansha,False,Pass,...,0,0,0,0,0,0,0,0,0,0

In [160]:
df_title_test.to_csv('title_no_duplicate.csv')

## Check how many rows were duplicated in scanlator dataframe

In [135]:
df_scanlator_full = pd.read_csv('scanlator_all.csv')
df_scanlator_full

,Unnamed: 0,Unnamed: 0.1,Name,Active or not,Release Frequency,Number of Release,Total Series,First Update,Lastest Update,Action,...,Shoujo Ai,Shounen,Shounen Ai,Slice of Life,Smut,Sports,Supernatural,Tragedy,Yaoi,Yuri
0,0,0,#1onlii,No,Inactive Group,9,9,01/03/15,03/22/15,2,...,0,4,0,2,0,0,3,1,0,0
1,1,0,#dropout,Yes,Often. About every 3.2 day(s),1033,26,08/02/16,08/03/20,3,...,0,13,0,10,0,0,8,0,0,0
2,2,0,#EverydayHeroes Scans,Yes,Often. About every 5.2 day(s),392,12,08/29/15,08/01/20,3,...,0,0,0,2,0,1,3,0,0,0
3,3,0,#got-nyu?,No,Inactive Group,0,0,no date,no date,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,#Hassasin,No,Inactive Group,4,2,05/23/19,12/30/19,1,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9893,18,0,김지우JK,Yes,Often. About every 4 day(s),17,1,06/15/19,08/04/20,1,...,0,1,0,0,0,0,0,1,0,0
9894,19,0,잠깐만,No,Inactive Group,1,1,02/03/20,02/03/20,1,...,0,1,0,0,0,0,0,0,0,0
9895,20,0,情深緣淺 Tinh Tham Duyen Thien,Yes,Infrequently,4,3,03/15/20,06/23/20,0,...,0,0,1,2,0,0,3,1,3,0
9896,21,0,灰猫,Yes,Often. About every 1 to 2 day(s),5,1,06/12/20,06/24/20,0,...,0,0,1,0,0,0,0,0,0,0
9897,22,0,顔掌 Translations,No,Inactive Group,3,1,08/17/10,08/03/12,1,...,0,1,0,0,0,0,0,0,0,0

In [136]:
list_scanlator_name = [i for i in df_scanlator_full['Name']]

In [138]:
set([x for x in list_scanlator_name if list_scanlator_name.count(x) > 1])

{'CHIREIJI',
 'Chinese BL Novel Translations',
 'Chinjufu Scanlations',
 'Chinkara',
 'Chinkos',
 'Chin² Scanlations',
 'ChireSakura',
 'Chiri Star',
 'Chirika',
 'Hikki no Mori Translations',
 'Hikoki Translations',
 'Penny Theater',
 'Zamazenta Scans',
 'chiochan03',
 'chiriwaka'}

In [144]:
len(set([x for x in list_scanlator_name if list_scanlator_name.count(x) > 1]))

15

## Drop the duplicated rows in scanlator dataframe

In [149]:
df_scanlator_full2 = df_scanlator_full.copy()

In [150]:
df_scanlator_full2 = df_scanlator_full2.drop_duplicates(subset='Name')

In [151]:
df_scanlator_full2

,Unnamed: 0,Unnamed: 0.1,Name,Active or not,Release Frequency,Number of Release,Total Series,First Update,Lastest Update,Action,...,Shoujo Ai,Shounen,Shounen Ai,Slice of Life,Smut,Sports,Supernatural,Tragedy,Yaoi,Yuri
0,0,0,#1onlii,No,Inactive Group,9,9,01/03/15,03/22/15,2,...,0,4,0,2,0,0,3,1,0,0
1,1,0,#dropout,Yes,Often. About every 3.2 day(s),1033,26,08/02/16,08/03/20,3,...,0,13,0,10,0,0,8,0,0,0
2,2,0,#EverydayHeroes Scans,Yes,Often. About every 5.2 day(s),392,12,08/29/15,08/01/20,3,...,0,0,0,2,0,1,3,0,0,0
3,3,0,#got-nyu?,No,Inactive Group,0,0,no date,no date,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,#Hassasin,No,Inactive Group,4,2,05/23/19,12/30/19,1,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9893,18,0,김지우JK,Yes,Often. About every 4 day(s),17,1,06/15/19,08/04/20,1,...,0,1,0,0,0,0,0,1,0,0
9894,19,0,잠깐만,No,Inactive Group,1,1,02/03/20,02/03/20,1,...,0,1,0,0,0,0,0,0,0,0
9895,20,0,情深緣淺 Tinh Tham Duyen Thien,Yes,Infrequently,4,3,03/15/20,06/23/20,0,...,0,0,1,2,0,0,3,1,3,0
9896,21,0,灰猫,Yes,Often. About every 1 to 2 day(s),5,1,06/12/20,06/24/20,0,...,0,0,1,0,0,0,0,0,0,0
9897,22,0,顔掌 Translations,No,Inactive Group,3,1,08/17/10,08/03/12,1,...,0,1,0,0,0,0,0,0,0,0

In [161]:
df_scanlator_full2.to_csv('scanlator_not_duplicated.csv')